### ISSUE TITLE
[BUG] Bugs and typos exist in /libresbc/tree/master/build/shell/installation.debian.sh

### ISSUE THREAD

**Issue by pcaveness** [hnimminh/libresbc#154]
**Describe the bug**
Bugs and typos exist in /libresbc/tree/master/build/shell/installation.debian.sh

**To Reproduce**
Run script elevated or as root from debian 11.9 console on a new installation.

**Actual behavior**
Failures to install correctly due to typos or other errors.

**Additional context**
Line1
Bad: !#/bin/bash
Fix: #!/bin/bash
Reason: typo

Line 7, 8
Bad: app-get install
Fix: apt-get install
Reason: app-get is invalid syntax

Line 25:
Bad: TOKEN = 'SIGNALWISE-PAT-TOKEN'
Fix: TOKEN='SIGNALWISE-PAT-TOKEN'
Reason: spaces break the variable.

Line 122-132:
Bad: Python 3.8.9 install fails, breaks paths, apt, other programs like ufw
Fix: Set variable before install: CFLAGS="$CFLAGS -g -O0 -Wno-error -fcommon"
Reason: installing 3.8.9 breaks python paths if this variable is not set before hand.

Line 151, 152, 153:
Bad: kamailio-5.5.1
Fix: kamailio-5.5.7
Reason: 5.5.1 is no longer in the latest-5.5.x directory.

Line 170, 171, 172:
Bad: captagent-6.3.1 issue installing. 
Fix: Set variable before install: CFLAGS="$CFLAGS -g -O0 -Wno-error -fcommon"
Reason: seems to be fixed in following versions, but captagent fails to install on Debian 11 due to an error in configure.ac of captagent 6.3.1 if this variable is not set.

**Comment by hnimminh** [comment]
@pcaveness `installation.debian.sh` is deprecated. 
Please consider to use ansible to install https://github.com/hnimminh/libresbc/wiki/Installation
or simple option is https://hub.docker.com/r/hnimminh/libresbc
