### ISSUE TITLE
[REQUEST] SIPREC (SIP Recording)

### ISSUE THREAD

**Issue by hungtr97** [hnimminh/libresbc#158]
Many enterprises SBC support SIPREC to utilize external call recording.
It would be great if LibreSBC could have these feature.

More details about SIPREC: https://datatracker.ietf.org/doc/id/draft-portman-siprec-protocol-01.html

**Comment by hnimminh** [comment]
@hungtr97 as I understand, you wish LibreSBC act as an SIPREC client, to fork an audio to remote SIPREC server. Are you able to provide a SIPREC server for testing and developing function? 
anyway, PR for this function is welcome.

**Comment by hnimminh** [comment]
closed as no response
