### ISSUE TITLE
[BUG]After receiving 183 and then receiving UPDATE, sbc can only implement single-pass problems

### ISSUE THREAD

**Issue by westice007** [hnimminh/libresbc#164]
**Describe the bug**
If there is no 183, INVITE is directly collected, and the call is normal.
However, when has 183, and the peer end sends the INVITE instead of the UPDATE message, the ringing number of 183 can be heard, and the peer end can hear my voice, but I cannot hear the voice of the peer party, and no RTP data from the peer party to the sbc can be queried

It seems that the sbc did not process and forward the UPDATE instruction

![image](https://github.com/hnimminh/libresbc/assets/6076502/0db4b13f-18a4-4f00-b142-3b878fb8ca94)

**Comment by hnimminh** [comment]
@westice007  could you please send me pcap file?

**Comment by hnimminh** [comment]
closed as no update
