### ISSUE TITLE
[BUG] nodeID may contain "-" at setup, while "-" is not allowed in members

### ISSUE THREAD

**Issue by bhoeneis** [hnimminh/libresbc#165]
**Describe the bug**
At install `nodeID` may contain "-" at setup. The `nodeID` appears to be the same (unchangable) string used for`member`  / `members`. While "Refine Cluster" still allows "-" in `members`, other functions, such as "NetAlias" with "-" in `member` are rejected as "-" it is not part of the RegExp string. 

**To Reproduce**
* Steps to reproduce the behavior
  * Install libresbc via ansible using nodeID **dev-sbc01**
  * Redine Cluster using **dev-sbc01** in `members` [works fine]
  * Create new NetAlias using **dev-sbc01** as `member` in `addresses` [ -> undefined ]
     `2024-08-27T13:35:48.739649+00:00 dev-sbc01 libresbc 159600 INFO  space=httpapi, action=middleware, processtime=0.002, requestid=63ec3a16-6622-4123-9305-c73c0d21958c, clientip=192.168.22.203, request=post:/libreapi/base/netalias, status_code=422, response_body={"detail":[{"loc":["body","addresses",0,"member"],"msg":"string does not match regex \"^[a-zA-Z][a-zA-Z0-9_]+$\"","type":"value_error.str.regex","ctx":{"pattern":"^[a-zA-Z][a-zA-Z0-9_]+$"}}]}`

**Actual behavior**
* see above

**Expected behavior**
* Either:
   * Allow "-" in all  `member`  / `members` (preferred)
   * Disallow "-" in NodeID at Install
   * Allow `member`  / `members` to have a different string as `NodeID` in Configuration (Not sure this is already possible, though did not find any documentation on this)

**Log & Screenshots**
* See above

**Additional context**
* Add any other context about the problem here, such as:
  * Version: eg. v0.7.1
  * OS: Debian GNU/Linux 11 (bullseye)

**Comment by hnimminh** [comment]
@bhoeneis could you please try with latest version  (master or v0.7.1.f)?

**Comment by hnimminh** [comment]
closed as no response
