### ISSUE TITLE
Docker Installation issue

### ISSUE THREAD

**Issue by spudgun1001** [hnimminh/libresbc#166]
I am using the latest version of Docker and Ubuntu 20.04.

I have installed the libreSBC Docker image and I have ran docker compose.

When I try and run the docker, I get this error.

root@sbc:~/libresbc/build/docker# docker run  hnimminh/libresbc
Traceback (most recent call last):
  File "/opt/libresbc/liberator/main.py", line 13, in <module>
    from configuration import REDIS_HOST, REDIS_PORT, REDIS_PASSWORD, REDIS_DB, NODEID, HTTPCDR_ENDPOINTS, DISKCDR_ENABLE, CDRFNAME_INTERVAL, CDRFNAME_FMT
  File "/opt/libresbc/liberator/configuration.py", line 103, in <module>
    NODEID_CHANNEL = f'{NODEID.upper()}_CHANNEL'
AttributeError: 'NoneType' object has no attribute 'upper'

I cannot seem to find where these files are located, as /opt does not contain a libresbc folder so I am unsure where it is getting these directories.

**Comment by hnimminh** [comment]
@spudgun1001  if you just get start to using libresbc or don't know how to setup libresbc with docker properly, please use [docker-compose.yml](https://github.com/hnimminh/libresbc/blob/master/build/docker/docker-compose.yml )

**Comment by spudgun1001** [comment]
I have installed docker, I have put the docker-compose.yml file and ran the compose file.

![image](https://github.com/user-attachments/assets/01befd26-8b30-439d-9e3e-a027e75ad792)

I am encountered with this error. What have I missed?

**Comment by spudgun1001** [comment]
> I have installed docker, I have put the docker-compose.yml file and ran the compose file.
> 
> ![image](https://private-user-images.githubusercontent.com/48835529/362784985-01befd26-8b30-439d-9e3e-a027e75ad792.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5NDg1MjksIm5iZiI6MTcyNDk0ODIyOSwicGF0aCI6Ii80ODgzNTUyOS8zNjI3ODQ5ODUtMDFiZWZkMjYtOGIzMC00MzlkLTllM2UtYTAyN2U3NWFkNzkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDE2MTcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxNjcxMjcwNjc4NmU1NzQ3YTVhYTc5ZGY4OTRhMGU5MDk5NmEyNDU3NTIwNTgwZTg0NWQyZDc5MTNhZjUzNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SCKzPNgOWttudr90Uo8n6MB4S3uWfEh6qQ5e5wWU0eI)
> 
> I am encountered with this error. What have I missed?

Figured it out, you need to extract the files into the container and then "docker compose up"
