### ISSUE TITLE
Netfilter table LIBREFW globaly blocks IPv6

### ISSUE THREAD

**Issue by hb9eue** [hnimminh/libresbc#170]
Hi

After installing libreSBC on a lab machine, I noticed that the machine had become unreachable via ip (actual IPv6, not that legacy IPv4 stuff :-) ) 

It took me quite some time, to figure out, that libreSBC had created a Netfilter Table inet LIBREFW with an INBOUND chain which defaults to drop and does not create and rules allowing IPv6. There is a rule allowing ssh via IPv4 from any which also sound a big dangerous to me.

We have not figured out how / where to change those rules, or disable those rules at all as we usually use ansible managed UFW as firewall on all our machines.

So not use if we missed where to configure this, or if this is hardcoded somewhere, therefore most probably a bug.

-Benoît-

**Comment by hnimminh** [comment]
I think it just a different mindset/idea on how manage firewall, LibreSBC follow the rule: 
* block all and allow later
* libresbc should run on dedicated machine not the shared one, mean you allow only what you need.

for ssh, it is not allow as default, it is in `/etc/preset.libre.nft` and customisable via ansible when you installing, also there is API to manage firewall as well.

However I'm open to any suggestion, and PR/commit change request.

**Comment by hnimminh** [comment]
Closed as no response!
