### ISSUE TITLE
[BUG] kamailio didnt start on master-branch

### ISSUE THREAD

**Issue by khorsmann** [hnimminh/libresbc#21]
**Describe the bug**
kamailio didnt start on master-branch

**To Reproduce**
build the master on fresh install - kamailio didnt run - ansible playbook didnt create some systemd.service or something that starts the process.

**Expected behavior**
all services should be started.

Best
Karsten

**Comment by hnimminh** [comment]
Hi @khorsmann 
By default there is only freeswitch service is will come up,  the Kamailio will spawn once access layer is defined.
Access service is defined via the api `libreapi/access/service`
