### ISSUE TITLE
[BUG]install failed on task [platform : build bcg729]

### ISSUE THREAD

**Issue by bcahyadi** [hnimminh/libresbc#36]
**Describe the bug**
ansible was stopped to install LibreSBC

**To Reproduce**
* Steps to reproduce the behavior
tried to install on debian 10.11 it's failed as well with the same reason failed to build bcg729

**Log & Screenshots**
* please find the log in the attached file below:
[libreSBC_install_failed.log](https://github.com/hnimminh/libresbc/files/7590594/libreSBC_install_failed.log)

**Additional context**
* Ansible server:
root@ansible:~/libresbc/build/ansible/ ansible --version
ansible [core 2.11.6]
  config file = /root/libresbc/build/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
  jinja version = 2.11.3
  libyaml = True

* LibreSBC server:
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
root@libresbc-id:  python --version
Python 2.7.18
root@libresbc-id: python3 --version
Python 3.9.2

**Comment by bcahyadi** [comment]
issue resolved after installing cmake package

**Comment by hnimminh** [comment]
thanks @bcahyadi, I will add task for install cmake soon
