### ISSUE TITLE
[Feature Request] API Requests

### ISSUE THREAD

**Issue by Legomix13** [hnimminh/libresbc#43]
**Describe the bug**
I'm building a web interface to manage the config more visually (will be openly released once finished) but when I try to make a PUT request to the API so I can modify an object I get a CORS error because most of the common web browsers will send first an OPTIONS request to the server but this one is rejecting that request with the message:
{"detail":"Method Not Allowed"}
Is there an easy way to let these request go?

**To Reproduce**
* Steps to reproduce the behavior
  * step1: Send a PUT request to any of the API endpoints over a browser
  * step2: Watch console

**Actual behavior**
The API server refuses the OPTIONS preflight request from the browser

**Expected behavior**
The server should let pass the OPTIONS and handle CORS

**Comment by hnimminh** [comment]
@Legomix13 can you retry with master? I just put new code support to CORS. Thanks

**Comment by Legomix13** [comment]
Awesome, I will contact you once I finish the development

Many thanks!

**Comment by hnimminh** [comment]
Well note, I'm exciting to see your UI. :)
