### ISSUE TITLE
[Deployement] FreeSWITCH require SignalWise PATs

### ISSUE THREAD

**Issue by ibexnet** [hnimminh/libresbc#51]
**Describe the bug**
The installation via ansible fail with this message:
` "Failed to download key at https://files.freeswitch.org/repo/deb/debian-release/fsstretch-archive-keyring.asc: HTTP Error 401: Unauthorized" `

**To Reproduce**
* Steps to reproduce the behavior
  * step1:  follow the installation steps described on https://github.com/hnimminh/libresbc/blob/master/documents/Installation.md

**Actual behavior**
The installation process fail to download the fsstretch-archive-keyring.asc before installing the rquirement packages.
I saw that the file under the link https://files.freeswitch.org/repo/deb/debian-release/fsstretch-archive-keyring.asc is password protected.

**Expected behavior**
* The installation process finish without errors.

**Log & Screenshots**
* If applicable, add screenshots or log to help explain your problem.

**Additional context**
* Add any other context about the problem here, such as:
  * OS: Debian 10.12
  * ` Linux 1 4.19.0-20-amd64 #1 SMP Debian 4.19.235-1 (2022-03-17) x86_64 GNU/Linux `
  *

**Comment by ooliver1** [comment]
you should most definitely rename this issue to describe more

something like `Failed to download key at <url> HTTP Error 401: Unauthorized`

**Comment by hnimminh** [comment]
hmmm.., seem signalwire has changed, the require PAT to access their repo 
https://freeswitch.org/confluence/display/FREESWITCH/HOWTO+Create+a+SignalWire+Personal+Access+Token

**Comment by camglegg** [comment]
Also running into this issue. I am able to create the PAT.

It seems that Freeswitch already has [Ansible playbook premade](https://freeswitch.org/confluence/display/FREESWITCH/Ansible+playbook+to+update+your+Debian+repository+to+add+a+SignalWire+Token). There suggestion is:

``` bash

# You could set the password here or on your CLI. We set it in group_vars/all in our Ansible Inventory
#  vars:
#    - signalwire_freeeswitch_key: pat_XXXXX

```

**Comment by hnimminh** [comment]
@camglegg I will add that support libresbc deployment in this weekend, once done, I will need your help to verify the fix.
I'm also thinking that use Docker, so that everyone can deploy libresbc easier.

**Comment by camglegg** [comment]
> @camglegg I will add that support libresbc deployment in this weekend, once done, I will need your help to verify the fix.
> I'm also thinking that use Docker, so that everyone can deploy libresbc easier.

I am more than happy to test the Ansible and Docker configurations!

I was working on updating the freeswitch.yml platform task, but there is quite a bit going on in that file. It will most likely be faster for you to update it.

I really appreciate your help!! Let me know if there is anything you need from me.

**Comment by hnimminh** [comment]
@camglegg @ibexnet can you re-test on master branch?

Once you register and get SignalWire Personal Access Tokens, you will need to declare ansible extra variable to install FreeSWITCH (when you run ansible-playbook with tag platform or freeswitch), Example:

`ansible-playbook playbooks/deployment.yml -i inventories/production -l "<machine-name>" -t "platform,libre,nginx,captagent" -e "signalwire_pat_token=Your-SignalWire-Personal-Access-Tokens"
`

**Comment by camglegg** [comment]
> @camglegg @ibexnet can you re-test on master branch?
> 
> Once you register and get SignalWire Personal Access Tokens, you will need to declare ansible extra variable to install FreeSWITCH (when you run ansible-playbook with tag platform or freeswitch), Example:
> 
> `ansible-playbook playbooks/deployment.yml -i inventories/production -l "<machine-name>" -t "platform,libre,nginx,captagent" -e "signalwire_pat_token=Your-SignalWire-Personal-Access-Tokens"
> `
> 

Yes! I will test this today. Thanks!

**Comment by camglegg** [comment]
@hnimminh The playbook works **perfectly**! 

**Target Machine**:
**OS**: Debian GNU/Linux 10 (Buster) x86_64
**Host**: KVM/QEMU
**Kernel**: 4.19.0.20-amd64

**Host Machine**
**Ansible Version**: 2.10.8
**Python Version**: 3.10.4

**Playbook Runtime**: 00:30:40

Let me know if you need anymore information and Thank you for the quick fix!

Full Log File (PAT Token Removed)
[cameronglegg_FreeSwitchPAT_ansible.log](https://github.com/hnimminh/libresbc/files/8840582/ansible.log)

**Comment by hnimminh** [comment]
Thanks @camglegg
