### ISSUE TITLE
[BUG] every installation will show fatal: [voiptcel]: FAILED! => {"msg": "Failed to connect to the host via ssh: ssh: connect to host X.X.X.X port 22: Connection timed out"}

### ISSUE THREAD

**Issue by rahman77889** [hnimminh/libresbc#59]
Hi 

I have follow the installation process and wait so long time during process installation

but will show error 
2022-07-20 01:46:47,808 p=6612 u=vassupport n=ansible | fatal: [voiptcel]: FAILED! => {"msg": "Failed to connect to the host via ssh: ssh: connect to host X.X.X.X port 22: Connection timed out"}
2022-07-20 01:46:47,808 p=6612 u=vassupport n=ansible | RUNNING HANDLER [nginx : restart nginx] ****************************************
2022-07-20 01:46:47,809 p=6612 u=vassupport n=ansible | NO MORE HOSTS LEFT *************************************************************
2022-07-20 01:46:47,810 p=6612 u=vassupport n=ansible | PLAY RECAP *********************************************************************

then I try again and again it still shows same things

what I have to do, to solve it

please help me
Thank you so much

**Comment by hnimminh** [comment]
Look like your ansible unable to access host due to mis-configuration of firewall.

**Comment by rahman77889** [comment]
Okay it's running now

i change config on file inventories/production/hosts.yml 
set ansible_host to 127.0.0.1

but now show another issue : 

TASK [captagent : Copy captagent role source to target host] ***************************************************************************************************************************************************************************
fatal: [voiptcel]: FAILED! => {"changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --rsync-path='sudo -u root rsync' --out-format='<<CHANGED>>%i %n%L' /home/user/libresbc/third-party/captagent/ /opt/libresbc/0.5.9/third-party/captagent/", "msg": "rsync: change_dir#1 \"/opt/libresbc/0.5.9/third-party/captagent/\" failed: Permission denied (13)\nrsync error: errors selecting input/output files, dirs (code 3) at main.c(639) [Receiver=3.1.3]\n", "rc": 3}

PLAY RECAP *****************************************************************************************************************************************************************************************************************************
voiptcel                   : ok=9    changed=4    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

why can it happen?

in another issue you said : 
"or the rsync issue, seems like the permission issue that ssh user was not able become root user. unable to reproduce on my side."

but how to solve it, I can't get it

please help me
Thank you so much
