### ISSUE TITLE
[BUG] failed rsync

### ISSUE THREAD

**Issue by rahman77889** [hnimminh/libresbc#60]
Hi @hnimminh 

while installation show as bellow 

TASK [captagent : Copy captagent role source to target host] ***************************************************************************************************************************************************************************
fatal: [voiptcel]: FAILED! => {"changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --rsync-path='sudo -u root rsync' --out-format='<<CHANGED>>%i %n%L' /home/user/libresbc/third-party/captagent/ /opt/libresbc/0.5.9/third-party/captagent/", "msg": "rsync: change_dir#1 \"/opt/libresbc/0.5.9/third-party/captagent/\" failed: Permission denied (13)\nrsync error: errors selecting input/output files, dirs (code 3) at main.c(639) [Receiver=3.1.3]\n", "rc": 3}

PLAY RECAP *****************************************************************************************************************************************************************************************************************************
voiptcel                   : ok=9    changed=4    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

why can it happen?

i use ansible version : 
ansible [core 2.11.12] 
  config file = None
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/lib/python3.7/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/.local/bin/ansible
  python version = 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]
  jinja version = 3.0.1
  libyaml = True

and I've been using config sudoers like this : 
ALL=(ALL:ALL) ALL
and
ALL=(ALL) NOPASSWD: ALL

but still not work

even if I use remote user as root, it still failed

and I have try with this command : 
ansible-playbook playbooks/deployment.yml  -kK -i inventories/production -l "voiptcel" -t "captagent"  -e "signalwire_pat_token=pat_eu7G8e1N5k3KVyC6Lk1XXXXX"
to prompt become password, but still failed

in another issue you said : 
"or the rsync issue, seems like the permission issue that ssh user was not able become root user. unable to reproduce on my side."

but how to solve it, I can't get it

please help me
Thank you so much

**Comment by hnimminh** [comment]
can not reproduce the issue on my side, 
if you don't mind, I may access you system to see what wrong with that.

**Comment by rahman77889** [comment]
problem solved, i change VM from debian 10 buster on Digital Ocean then now install VM debian 10 buster on azure

rsync issue not found but, it goes so long process

until now it takes 4 hours, log ansible there's no moving

but if I check on top, still running ansible-playbook

2022-07-22 10:28:35,685 p=9408 u=azureuser n=ansible | changed: [voiptcel] => (item={'src': '/opt/libresbc/0.5.9/third-party/captagent', 'dest': '/usr/local/captagent/etc/captagent'})
2022-07-22 10:28:35,699 p=9408 u=azureuser n=ansible | TASK [captagent : handle restart captagent daemon] *****************************
2022-07-22 10:28:35,719 p=9408 u=azureuser n=ansible | skipping: [voiptcel]
2022-07-22 10:28:35,744 p=9408 u=azureuser n=ansible | RUNNING HANDLER [libre : restart liberator] ************************************
2022-07-22 10:28:36,442 p=9408 u=azureuser n=ansible | changed: [voiptcel]
2022-07-22 10:28:36,443 p=9408 u=azureuser n=ansible | RUNNING HANDLER [libre : restart rsyslog] **************************************
2022-07-22 10:28:37,163 p=9408 u=azureuser n=ansible | changed: [voiptcel]
2022-07-22 10:28:37,164 p=9408 u=azureuser n=ansible | RUNNING HANDLER [libre : reload logrotate] *************************************

is there any solution now?

**Comment by rahman77889** [comment]
> 
update info 

finally finished installation after 4 hour 30 / minutes

problem solved now

thank you for your response @hnimminh
