### ISSUE TITLE
[BUG] Unable to delete unengaged routing table

### ISSUE THREAD

**Issue by cnickh** [hnimminh/libresbc#80]
**Describe the bug**
Unable to delete routing table that is no longer in use.

**To Reproduce**

Add routing table **RoutingTableA** and add inbound connection **InboundA** using **RoutingTableA**. 

LibreSBC will not allow you to remove the **RoutingTableA** while engaged with **InboundA**. However even when **InboundA** is deleted it is still impossible to remove **RoutingTableA**.

**Actual behavior**
Once **InboundA** was deleted, attempting a DELETE on **RoutingTableA** returns: 

{
  "error": "engaged routing table"
}

despite the inbound connection being deleted.

**Expected behavior**
The Routing table should be able to be deleted once the engaged inbound connection is deleted.

**Log & Screenshots**
<img width="691" alt="libre-err" src="https://user-images.githubusercontent.com/36873138/207960512-4813e92d-2834-4c4d-a964-7167a2502d46.PNG">

The screenshot shows no registered inbound connections. But DELETE not succeeding on the routing table 'toSIPP12'.

**Additional context**
  * Version: eg. v0.5.9
  * OS: eg. Debian 10

**Comment by hnimminh** [comment]
Thanks @cnickh 
The issue is reproducible, found there a missing un-engage for routing of inbound interconnection. Will add the fix soon!

**Comment by hnimminh** [comment]
@cnickh just added the fix, can you re-add the SIPP11 and reproduce issue. Thanks
