### ISSUE TITLE
Better handling (restrict) nodename convention 

### ISSUE THREAD

**Issue by hnimminh** [hnimminh/libresbc#83]
take a look on https://github.com/hnimminh/libresbc/discussions/81 for more detail

**Comment by poldy42** [comment]
Good morning,
is there a change to the node name restrictions here? This is coming to my attention because our hosts are named according to the "xx-yy-zzz-0001" pattern and a new name assignment would be difficult to handle... Is there any reason to restrict the names that way ?
Cheers - Michael

**Comment by hnimminh** [comment]
@poldy42 thanks for reminder, I will review and make a fix in this weekend.
