### ISSUE TITLE
Video and WebRTC support

### ISSUE THREAD

**Issue by pengweichu** [hnimminh/libresbc#9]
**Is your feature request related to a problem? Please describe.**
* A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Does the libresbc is supporting Video calls and WebRTC?

**Describe the solution you'd like**
* A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
* A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
* Add any other context or screenshots about the feature request here.

**Comment by hnimminh** [comment]
SIP over Websocket is in roadmap already.
For Video can you elaborate more on the usecase?

**Comment by hnimminh** [comment]
closed as no replied.
