### ISSUE TITLE
[BUG] Update sipprofile API

### ISSUE THREAD

**Issue by jj1682000** [hnimminh/libresbc#94]
**Describe the bug**

Can not update below:
  "enable_timer"
  "session_timeout"
  "minimum_session_expires"

**To Reproduce**
* Steps to reproduce the behavior
  * step1:  PUT https://sbc02.sample.com:8443/libreapi/sipprofile/sipprofile_FS_loopback
  {
  "name": "sipprofile_FS_loopback",
  "desc": "sipprofile_FS_loopback",
  "user_agent": "LibreSBC",
  "sdp_user": "LibreSBC",
  "local_network_acl": "nat.auto",
  "enable_100rel": false,
  "ignore_183nosdp": true,
  "sip_options_respond_503_on_busy": true,
  "disable_transfer": false,
  "manual_redirect": false,
  "enable_3pcc": false,
  "enable_compact_headers": false,
  "enable_timer": false,
  "session_timeout": 1800,
  "minimum_session_expires": 120,
  "dtmf_type": "rfc2833",
  "media_timeout": 1800,
  "rtp_rewrite_timestamps": false,
  "context": "access",
  "sip_port": 5080,
  "sip_address": "netalias_FS_loopback",
  "rtp_address": "netalias_external",
  "tls": false,
  "tls_only": false,
  "sips_port": 5061
}
  * step2: GET https://sbc02.sample.com:8443/libreapi/sipprofile/sipprofile_FS_loopback
  {
    "name": "sipprofile_FS_loopback",
    "desc": "sipprofile_FS_loopback",
    "user_agent": "LibreSBC",
    "sdp_user": "LibreSBC",
    "local_network_acl": "nat.auto",
    "enable_100rel": false,
    "ignore_183nosdp": true,
    "sip_options_respond_503_on_busy": true,
    "disable_transfer": false,
    "manual_redirect": false,
    "enable_3pcc": false,
    "enable_compact_headers": false,
    "dtmf_type": "rfc2833",
    "media_timeout": 1800,
    "rtp_rewrite_timestamps": false,
    "context": "access",
    "sip_port": 5080,
    "sip_address": "netalias_FS_loopback",
    "rtp_address": "netalias_external",
    "tls": false,
    "tls_only": false,
    "sips_port": 5061,
    "tls_version": "tlsv1.2",
    "realm": "sipprofile_FS_loopback.libresbc",
    "engagements": [
        "in:interconnection_loopback"
    ]
    }
Can not find below in detail result:

  "enable_timer"
  "session_timeout"
  "minimum_session_expires"

**Actual behavior**
Detail sipprofile:

{
    "name": "sipprofile_FS_loopback",
    "desc": "sipprofile_FS_loopback",
    "user_agent": "LibreSBC",
    "sdp_user": "LibreSBC",
    "local_network_acl": "nat.auto",
    "enable_100rel": false,
    "ignore_183nosdp": true,
    "sip_options_respond_503_on_busy": true,
    "disable_transfer": false,
    "manual_redirect": false,
    "enable_3pcc": false,
    "enable_compact_headers": false,
    "dtmf_type": "rfc2833",
    "media_timeout": 1800,
    "rtp_rewrite_timestamps": false,
    "context": "access",
    "sip_port": 5080,
    "sip_address": "netalias_FS_loopback",
    "rtp_address": "netalias_external",
    "tls": false,
    "tls_only": false,
    "sips_port": 5061,
    "tls_version": "tlsv1.2",
    "realm": "sipprofile_FS_loopback.libresbc",
    "engagements": [
        "in:interconnection_loopback"
    ]
}

**Expected behavior**
Detail sipprofile:
{
    "name": "sipprofile_FS_loopback",
    "desc": "sipprofile_FS_loopback",
    "user_agent": "LibreSBC",
    "sdp_user": "LibreSBC",
    "local_network_acl": "nat.auto",
    "enable_100rel": false,
    "ignore_183nosdp": true,
    "sip_options_respond_503_on_busy": true,
    "disable_transfer": false,
    "manual_redirect": false,
    "enable_3pcc": false,
    "enable_compact_headers": false,
    "dtmf_type": "rfc2833",
    "media_timeout": 1800,
    "rtp_rewrite_timestamps": false,
    "context": "access",
    "sip_port": 5080,
    "sip_address": "netalias_FS_loopback",
    "rtp_address": "netalias_external",
    "tls": false,
    "tls_only": false,
    "sips_port": 5061,
    "tls_version": "tlsv1.2",
    "realm": "sipprofile_FS_loopback.libresbc",
    "engagements": [
        "in:interconnection_loopback"
    ]
}

**Log & Screenshots**
* If applicable, add screenshots or log to help explain your problem.

**Additional context**
* Add any other context about the problem here, such as:
  * Version: LibreSBC v0.5.9 Release
  * OS: Debian 10
  * Interworking System: None

**Comment by hnimminh** [comment]
it is not a bug, when enable_timer = false, `'enable_timer', 'session_timeout', 'minimum_session_expires'` will be removed since it it default setting as disabling.

what is different between  Expected & Actual, can you highlight them?

**Comment by jj1682000** [comment]
sorry, this is correct Expected:

  {
  "name": "sipprofile_FS_loopback",
  "desc": "sipprofile_FS_loopback",
  "user_agent": "LibreSBC",
  "sdp_user": "LibreSBC",
  "local_network_acl": "nat.auto",
  "enable_100rel": false,
  "ignore_183nosdp": true,
  "sip_options_respond_503_on_busy": true,
  "disable_transfer": false,
  "manual_redirect": false,
  "enable_3pcc": false,
  "enable_compact_headers": false,
  **"enable_timer": false,
  "session_timeout": 1800,
  "minimum_session_expires": 120,**
  "dtmf_type": "rfc2833",
  "media_timeout": 1800,
  "rtp_rewrite_timestamps": false,
  "context": "access",
  "sip_port": 5080,
  "sip_address": "netalias_FS_loopback",
  "rtp_address": "netalias_external",
  "tls": false,
  "tls_only": false,
  "sips_port": 5061
}

**Comment by hnimminh** [comment]
when `enable_timer": false`, `session_timeout` and `minimum_session_expires` is not take effect. 
server will work as default behavior. (there fields removed). 
anyway if you want them appear event it is default. please open new enhancement or Pull Request are welcome.
